submap = os
bind = $mainMod, Q, exec, uwsm stop
# use reset to go back to the global submap
bind = CTRL, bracketleft, submap, reset
bind = , escape, submap, reset
# will reset the submap, which will return to the global submap
submap = reset
