submap = picker, reset
# Clipboard
bind = , C, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
# Hyprpicker ~= (P)icker > (H)ypr
bind = , H, exec, uwsm-app -- hyprpicker -a
# use reset to go back to the global submap
bind = CTRL, bracketleft, submap, reset
bind = , escape, submap, reset
# will reset the submap, which will return to the global submap
submap = reset
