submap = win_prop
bind = , A, setprop, active opaque toggle
bind = , A, submap, reset

bind = , B, setprop, active no_blur toggle
bind = , B, submap, reset

bind = , P, pin
bind = , P, submap, reset
#bind = , X, pseudo, # dwindle
#bind = , J, togglesplit, # dwindle
# use reset to go back to the global submap
bind = CTRL, bracketleft, submap, reset
bind = , escape, submap, reset
# will reset the submap, which will return to the global submap
submap = reset

