submap = zoom
bind = , mouse_down, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.05')
bind = , mouse_up, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.95) | if . < 1 then 1 else . end')

binde = , KP_Add, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.05')
binde = , KP_Subtract, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.95) | if . < 1 then 1 else . end')
# use reset to go back to the global submap
bind = CTRL, bracketleft, exec, hyprctl -q keyword cursor:zoom_factor 1
bind = CTRL, bracketleft, submap, reset
bind = , KP_Enter, submap, reset
bind = , escape, exec, hyprctl -q keyword cursor:zoom_factor 1
bind = , escape, submap, reset
# will reset the submap, which will return to the global submap
submap = reset
