$mainMod = SUPER # Sets "Windows" key as main modifier
#$terminal = uwsm-app -- kitty --single-instance
$terminal = uwsm-app -- kitty
$menu = rofi -show drun -run-command "uwsm-app -- {cmd}"

bind = $mainMod, T, exec, $terminal
bind = $mainMod, R, exec, $menu
bind = $mainMod, C, killactive,
#
# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, F, togglefloating,
bind = $mainMod, F, fullscreen
bind = $mainMod, A, setprop, active opaque toggle
#bind = $mainMod, P, pseudo, # dwindle
#bind = $mainMod, J, togglesplit, # dwindle


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

source = ~/.config/hypr/keybinds/workspace.conf
source = ~/.config/hypr/keybinds/multimedia.conf

# SUBMAPS
source = ~/.config/hypr/keybinds/submaps/*
bind = $mainMod SHIFT, R, submap, resize
bind = $mainMod , O, submap, os
bind = $mainMod , P, submap, picker
