wallpaper {
    monitor = DP-3
    path = ~/Pictures/wallpapers/DP-3.jxl
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/HDMI-A-1.jxl
    fit_mode = cover
}
