input {
    kb_model = pc104
    kb_layout = us, us
    kb_variant = dvp,
    kb_options = grp:win_space_toggle
    repeat_rate = 30
    repeat_delay = 200
    follow_mouse = 1
    numlock_by_default = true
    resolve_binds_by_sym = 1
    scroll_factor = 2.5
}
