# vim:ft=kitty

## name: C64-var2
## author: Ian Leng <https://github.com/ligmaleng>
## blurb: Inspired by Commodore64 color scheme.

# The basic colors
foreground                      #ffffff
background                      #191919
selection_foreground            #c6c6c6
selection_background            #979797

# Cursor colors
cursor                          #c6c6c6
cursor_text_color               #191919

# kitty window border colors
active_border_color     #a1683c
inactive_border_color   #6d5412

# Tab bar colors
active_tab_foreground   #f8faa1
active_tab_background   #5554a0
inactive_tab_foreground #5554a0
inactive_tab_background #8f8de3

# The basic 16 colors
# black
color0 #191919
# orange
color8 #9e7358

# red
color1 #925c5f
# light red
color9 #cb8e92

# green
color2  #7ebb78
# light green
color10 #c8ffc1

# light grey
color3  #c6c6c6
# yellow
color11 #f8faa1

# blue
color4  #5554a0
# light blue
color12 #8f8de3

# dark grey
color5  #6c6c6c
# violet
color13 #9e65a5

# mid grey
color6  #979797
# cyan
color14 #9cd9d6

# white
color7  #ffffff
# brown
color15 #705c2c
