# vim:ft=kitty

## name: C64-var3
## author: Ian Leng <https://github.com/ligmaleng>
## blurb: Inspired by Commodore64 color scheme.

# The basic colors
foreground                      #959595
background                      #000000 
selection_foreground            #959595
selection_background            #444444

# Cursor colors
cursor                          #b2b2b2
cursor_text_color               #000000 

# kitty window border colors
active_border_color     #6f3d86
inactive_border_color   #6c6c6c

# Tab bar colors
active_tab_foreground   #edf171
active_tab_background   #352879
inactive_tab_foreground #352879
inactive_tab_background #6c5eb5

# The basic 16 colors
# black
color0 #000000
# orange
color8 #6f4f25

# red
color1 #68372b
# light red
color9 #9a6759

# green
color2  #588d43
# light green
color10 #9ad284

# light grey
color3  #959595
# yellow
color11 #b8c76f

# blue
color4  #2e2c9b
# light blue
color12 #706deb

# mid grey
color5  #6c6c6c
# violet
color13 #6f3d86

# dark grey
color6  #444444
# cyan
color14 #70a4b2

# white
color7  #ffffff
# brown
color15 #433900
