pygments_style dracula
dark_pygments_style dracula
video_preview width=480 fps=10 duration=5

map esc quit
map ctrl+[ quit

map enter accept
map ctrl+m accept

map ctrl+space select

map ctrl+/ typename
map ctrl+enter typename


map up next -1
map down next 1
map left next left
map right next right

map ctrl+p next -1
map ctrl+n next 1
map ctrl+h next left
map ctrl+l next right


map home next first_on_screen
map ctrl+u next first_on_screen

map end next last_on_screen
map ctrl+d  next last_on_screen

map ctrl+g>g next first
map ctrl+g>ctrl+g next last

map alt+l cd .
map alt+h cd ..

map ctrl+g>/ cd /
map ctrl+g>h cd ~
map ctrl+g>t cd /tmp

map tab next_filter 1
map shift+tab next_filter -1
map ctrl+i next_filter 1
map ctrl+shift+i next_filter -1

map ctrl+t>. toggle dotfiles
map ctrl+t>i toggle ignorefiles
map ctrl+t>s toggle sort_by_dates
map ctrl+t>p toggle preview
